/**
 * Commission Engine - Automated Agent Commission Calculator
 * 
 * Runs periodically to calculate commissions for agents based on:
 * - Revenue share percentage from tenant config
 * - Closed trades by team members within the period
 * - Fee-based and PnL-based commission models
 * 
 * Schedule: Runs every 4 hours (configurable)
 */
const { pool } = require('../config/database');

class CommissionEngine {
  constructor() {
    this.intervalMs = parseInt(process.env.COMMISSION_INTERVAL_MS) || 4 * 60 * 60 * 1000; // 4 hours
    this.timer = null;
    this.isRunning = false;
    this.lastRun = null;
  }

  start() {
    console.log(`💰 Commission Engine started (interval: ${this.intervalMs / 1000 / 60} min)`);
    // Run once on startup after a delay
    setTimeout(() => this.run(), 30000); // 30s delay after boot
    this.timer = setInterval(() => this.run(), this.intervalMs);
  }

  stop() {
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
    console.log('💰 Commission Engine stopped');
  }

  async run() {
    if (this.isRunning) {
      console.log('💰 Commission Engine: Already running, skipping...');
      return;
    }

    this.isRunning = true;
    const startTime = Date.now();

    try {
      console.log('💰 Commission Engine: Starting calculation cycle...');

      // 1. Get all active agent tenants
      const tenantsResult = await pool.query(`
        SELECT t.id as tenant_id, t.name as tenant_name, t.owner_user_id, 
               t.revenue_share_pct, t.subscription_plan
        FROM tenants t
        WHERE t.is_active = true 
          AND t.owner_user_id IS NOT NULL
          AND t.revenue_share_pct > 0
      `);

      if (tenantsResult.rows.length === 0) {
        console.log('💰 Commission Engine: No active agent tenants found.');
        this.isRunning = false;
        this.lastRun = new Date();
        return;
      }

      let totalCommissions = 0;
      let totalAmount = 0;

      for (const tenant of tenantsResult.rows) {
        try {
          const result = await this.calculateTenantCommissions(tenant);
          totalCommissions += result.count;
          totalAmount += result.amount;
        } catch (err) {
          console.error(`💰 Commission Engine: Error for tenant ${tenant.tenant_id}:`, err.message);
        }
      }

      const elapsed = ((Date.now() - startTime) / 1000).toFixed(2);
      console.log(`💰 Commission Engine: Cycle complete in ${elapsed}s — ${totalCommissions} new commissions, $${totalAmount.toFixed(2)} total`);
      this.lastRun = new Date();
    } catch (err) {
      console.error('💰 Commission Engine: Critical error:', err);
    } finally {
      this.isRunning = false;
    }
  }

  /**
   * Calculate commissions for a specific tenant's agent
   * Commission is based on the gross fees generated by team members' trades
   */
  async calculateTenantCommissions(tenant) {
    const { tenant_id, owner_user_id, revenue_share_pct } = tenant;

    // Find trades that have been closed but not yet commissioned
    // We use a window: only trades closed since last commission calculation
    // or in the last 24 hours (whichever is later)
    const lastCommission = await pool.query(`
      SELECT MAX(trade_closed_at) as last_processed
      FROM agent_commissions
      WHERE agent_user_id = $1
    `, [owner_user_id]);

    const lastProcessed = lastCommission.rows[0]?.last_processed;
    const sinceDate = lastProcessed || new Date(Date.now() - 24 * 60 * 60 * 1000);

    // Get closed trades from team members that haven't been commissioned yet
    const tradesResult = await pool.query(`
      SELECT t.id as trade_id, t.pnl, t.commission as trade_fee, t.swap, 
             t.closed_at, a.user_id as trader_user_id,
             u.display_name as trader_name, u.username as trader_username,
             t.symbol, t.volume
      FROM trades t
      JOIN accounts a ON a.id = t.account_id
      JOIN users u ON u.id = a.user_id
      WHERE u.tenant_id = $1
        AND u.id != $2
        AND t.status = 'CLOSED'
        AND t.closed_at > $3
        AND t.id NOT IN (
          SELECT COALESCE(source_trade_id, 0) 
          FROM agent_commissions 
          WHERE agent_user_id = $2
        )
      ORDER BY t.closed_at ASC
      LIMIT 500
    `, [tenant_id, owner_user_id, sinceDate]);

    if (tradesResult.rows.length === 0) {
      return { count: 0, amount: 0 };
    }

    let totalAmount = 0;
    let insertCount = 0;

    for (const trade of tradesResult.rows) {
      try {
        // Commission calculation strategy:
        // Option A: Based on trading fees (commission + swap)
        // Option B: Based on positive PnL only
        // We use a hybrid: commission from fees if available, otherwise from PnL
        let commissionBase = 0;
        let commissionType = 'TRADE_FEE';

        const tradeFee = Math.abs(parseFloat(trade.trade_fee) || 0);
        const tradeSwap = Math.abs(parseFloat(trade.swap) || 0);
        const tradePnl = parseFloat(trade.pnl) || 0;

        if (tradeFee > 0 || tradeSwap > 0) {
          // Fee-based commission
          commissionBase = tradeFee + tradeSwap;
          commissionType = 'TRADE_FEE';
        } else if (tradePnl > 0) {
          // PnL-based commission (only on profitable trades)
          commissionBase = tradePnl;
          commissionType = 'TRADE_PNL';
        } else {
          // No commission for zero-fee losing trades
          continue;
        }

        const commissionAmount = commissionBase * (parseFloat(revenue_share_pct) / 100);

        if (commissionAmount < 0.01) continue; // Skip negligible amounts

        await pool.query(`
          INSERT INTO agent_commissions 
            (agent_user_id, tenant_id, source_user_id, source_trade_id, 
             commission_type, rate_pct, base_amount, amount, 
             trade_closed_at, status, created_at)
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'PENDING', NOW())
        `, [
          owner_user_id,
          tenant_id,
          trade.trader_user_id,
          trade.trade_id,
          commissionType,
          revenue_share_pct,
          commissionBase,
          commissionAmount,
          trade.closed_at
        ]);

        totalAmount += commissionAmount;
        insertCount++;
      } catch (err) {
        // Skip individual trade errors (e.g., duplicate) silently
        if (!err.message.includes('duplicate')) {
          console.error(`💰 Commission calc error for trade ${trade.trade_id}:`, err.message);
        }
      }
    }

    if (insertCount > 0) {
      console.log(`💰 Tenant "${tenant.tenant_name}": ${insertCount} commissions ($${totalAmount.toFixed(2)}) at ${revenue_share_pct}%`);
    }

    return { count: insertCount, amount: totalAmount };
  }

  /**
   * Settle pending commissions (admin action or scheduled)
   * Changes status from PENDING to SETTLED
   */
  async settlePendingCommissions(agentUserId = null) {
    try {
      let query = `
        UPDATE agent_commissions 
        SET status = 'SETTLED', settled_at = NOW()
        WHERE status = 'PENDING'
      `;
      const params = [];

      if (agentUserId) {
        query += ` AND agent_user_id = $1`;
        params.push(agentUserId);
      }

      query += ` RETURNING id, amount`;
      const result = await pool.query(query, params);

      const totalSettled = result.rows.reduce((sum, r) => sum + parseFloat(r.amount), 0);
      console.log(`💰 Settled ${result.rows.length} commissions ($${totalSettled.toFixed(2)})`);

      return {
        count: result.rows.length,
        total_amount: totalSettled,
      };
    } catch (err) {
      console.error('💰 Settle commissions error:', err);
      throw err;
    }
  }

  getStatus() {
    return {
      running: this.isRunning,
      lastRun: this.lastRun,
      intervalMs: this.intervalMs,
    };
  }
}

module.exports = new CommissionEngine();
