version: "3.8"

services:
  mt5-node-1:
    build: .
    container_name: nexusfx-mt5-node-1
    ports:
      - "8080:8080" # NoVNC Web Interface
      - "5900:5900" # VNC Direct
    volumes:
      - mt5-data-1:/root/.wine/drive_c/Program Files/MetaTrader 5
    restart: always

# You can add mt5-node-2, mt5-node-3 easily by copying the block above
# and changing the ports (e.g. 8081:8080, 5901:5900)

volumes:
  mt5-data-1:
