version: "3.8"

services:
  mt5-node-1:
    build: .
    container_name: nexusfx-mt5-node-1
    ports:
      - "8080:8080" # NoVNC Web Interface
      - "5900:5900" # VNC Direct
    volumes:
      - mt5-data-1:/root/.wine
      - ./../EA/Infra_Data:/root/ea-source/Infra_Data
    restart: always

  # === Node 2 (Uncomment to add) ===
  # mt5-node-2:
  #   build: .
  #   container_name: nexusfx-mt5-node-2
  #   ports:
  #     - "8081:8080"
  #     - "5901:5900"
  #   volumes:
  #     - mt5-data-2:/root/.wine
  #     - ./../EA/Infra_Data:/root/ea-source/Infra_Data
  #   restart: always

volumes:
  mt5-data-1:
  # mt5-data-2:
